languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "june.cx"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
dateFormat = "2 January 2006"

# mainSections = ["section1", "section2"]
description = "june's website"

[params.author]
name = "june"
image = "img/author.png"
headline = "the silliest"
bio = "she/they"
links = [
  { email = "mailto:june0925@proton.me" },
  { discord = "https://discord.com/users/1200112887537074306" },
  { github = "https://github.com/succumbs" },
  { steam = "https://steamcommunity.com/id/juniecat" },
  { youtube = "https://youtube.com/@junemeow" },
]
